table dimStore
	lineageTag: 3bebf645-8d40-4802-b6ab-9668689ec0b6

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 8d92ff98-c7c9-4dba-ac38-5451c6de852c
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column LocationKey
		dataType: double
		formatString: 0
		lineageTag: aac3729e-dc40-4e1e-b385-0aeb1126cd6c
		summarizeBy: none
		sourceColumn: LocationKey

		annotation SummarizationSetBy = Automatic

	column StoreManager
		dataType: int64
		formatString: 0
		lineageTag: a5db8b31-590e-4b97-b8b9-20dfe59a0918
		summarizeBy: sum
		sourceColumn: StoreManager

		annotation SummarizationSetBy = Automatic

	column StoreType
		dataType: string
		lineageTag: 12655d6e-55dd-4f45-a6ac-ab57c8c3803b
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StoreName
		dataType: string
		lineageTag: 245b9e17-5061-4a1f-ad9e-a26bd8ea92b4
		summarizeBy: none
		sourceColumn: StoreName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ZipCode
		dataType: string
		lineageTag: f81df1d6-f1c6-483a-add7-6df7eab2d311
		summarizeBy: none
		sourceColumn: ZipCode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StorePhone
		dataType: string
		lineageTag: 684738d4-815f-450a-a206-b97d04a485f2
		summarizeBy: none
		sourceColumn: StorePhone

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column AddressLine1
		dataType: string
		lineageTag: d3c93262-8ce4-4dbc-8a94-cad7f67693da
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column EmployeeCount
		dataType: int64
		formatString: 0
		lineageTag: f0131f1d-3dfe-4801-b994-378679e136a5
		summarizeBy: sum
		sourceColumn: EmployeeCount

		annotation SummarizationSetBy = Automatic

	column SellingAreaSize
		dataType: double
		lineageTag: 784df51a-3df3-4eef-b4b9-f12f2b597889
		summarizeBy: sum
		sourceColumn: SellingAreaSize

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dimStore-e2a3cd9c-34f5-44c4-a00b-6b92641e0aa9 = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = InputForDimTables,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"DimStore"}),
				    #"Expanded DimStore" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimStore", {"StoreKey", "GeographyKey", "StoreManager", "StoreType", "StoreName", "StoreDescription", "Status", "OpenDate", "CloseDate", "EntityKey", "ZipCode", "ZipCodeExtension", "StorePhone", "StoreFax", "AddressLine1", "AddressLine2", "CloseReason", "EmployeeCount", "SellingAreaSize", "LastRemodelDate", "GeoLocation", "Geometry"}, {"StoreKey", "GeographyKey", "StoreManager", "StoreType", "StoreName", "StoreDescription", "Status", "OpenDate", "CloseDate", "EntityKey", "ZipCode", "ZipCodeExtension", "StorePhone", "StoreFax", "AddressLine1", "AddressLine2", "CloseReason", "EmployeeCount", "SellingAreaSize", "LastRemodelDate", "GeoLocation", "Geometry"}),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded DimStore", {"StoreKey"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Duplicates",{{"StoreKey", Order.Ascending}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Sorted Rows",{"StoreKey", "GeographyKey", "StoreManager", "StoreType", "StoreName", "ZipCode", "StorePhone", "AddressLine1", "EmployeeCount", "SellingAreaSize"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Removed Other Columns1","North Harford St Shopping mall","Citycenter München, Germany",Replacer.ReplaceText,{"AddressLine1"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Replaced Value1",894,765,Replacer.ReplaceValue,{"GeographyKey"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value","Contoso","",Replacer.ReplaceText,{"StoreName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value2",{{"GeographyKey", "LocationKey"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation PBI_QueryRelationships = {"columnCount":10,"keyColumnNames":["StoreKey"],"queryRelationships":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimMachine.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactITSLA.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactInventory.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactOnlineSales.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactSales.{StoreKey,3}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactSalesQuota.{StoreKey,2}","KeyColumnCount":1}],"columnIdentities":["Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StoreKey,0}","Section1/dimStore/Replaced Value.{GeographyKey,1}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StoreManager,2}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StoreType,3}","Section1/dimStore/Replaced Value2.{StoreName,4}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{ZipCode,10}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StorePhone,12}","Section1/dimStore/Replaced Value1.{AddressLine1,7}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{EmployeeCount,17}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{SellingAreaSize,18}"],"ColumnCount":10,"KeyColumnNames":["StoreKey"],"ColumnIdentities":["Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StoreKey,0}","Section1/dimStore/Replaced Value.{GeographyKey,1}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StoreManager,2}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StoreType,3}","Section1/dimStore/Replaced Value2.{StoreName,4}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{ZipCode,10}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{StorePhone,12}","Section1/dimStore/Replaced Value1.{AddressLine1,7}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{EmployeeCount,17}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimStore.{SellingAreaSize,18}"],"RelationshipInfo":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimMachine.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactITSLA.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactInventory.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactOnlineSales.{StoreKey,2}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactSales.{StoreKey,3}","KeyColumnCount":1},{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/FactSalesQuota.{StoreKey,2}","KeyColumnCount":1}]}

