table 'Internet Sales'
	lineageTag: 2a661581-d356-40a6-8e24-3f22571a0ea2

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: daf6d977-418f-43f8-baa1-656de25cfe15
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 588b6ad8-1522-4a67-acdc-cd659ad428cb
		summarizeBy: count
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7ff0ed73-f858-4e49-8501-b8ed44d501f9
		summarizeBy: count
		sourceColumn: DueDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e7033299-3a5b-4eb6-a8de-7ce2a7be01b5
		summarizeBy: count
		sourceColumn: ShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 92ddec53-922a-4858-9877-326e3eda4f21
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5d408eba-8ddf-4fc3-8e0a-f8269390ba61
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: eaf76bbf-dad0-4b6f-b474-1c2f55980337
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: acc12af5-0368-4c22-8db2-260d13d48514
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: #,0
		lineageTag: 6a92abe2-2135-4fae-950c-3c4f2cb5a9fc
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 80ef0b07-300f-4c41-9c0a-d99be3ddfca6
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedAmount
		dataType: double
		lineageTag: d1a3bd0e-c499-45d1-9640-86c093f91fb0
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: int64
		formatString: 0
		lineageTag: e62205ee-3d6b-48fe-bc35-faaa1146a225
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

	column DiscountAmount
		dataType: int64
		formatString: 0
		lineageTag: 31a5a7fa-c941-4a93-8c0e-1d084425e889
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

	column ProductStandardCost
		dataType: double
		lineageTag: 3ae60c8a-ab64-4b7b-b16f-205efc6e7841
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalProductCost
		dataType: double
		lineageTag: d314d2c2-a1a6-4041-b4b3-8a0101b69bc4
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e4d3b5e1-25b5-4788-aee8-10b972bef573
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TaxAmt
		dataType: double
		lineageTag: 3cba7c8b-7001-4628-a08e-4c2c760936de
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Freight
		dataType: double
		lineageTag: ae97f699-608a-44d4-b1dc-1a90f08c0548
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CarrierTrackingNumber
		dataType: string
		lineageTag: adfe98bd-fd89-4dc2-a064-0de7656e0a51
		summarizeBy: none
		sourceColumn: CarrierTrackingNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3e6bd5e9-20d3-4e6e-9b75-4e48dc02982b
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac7e54a6-a582-4128-9d87-2db15564e6d0
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a706084f-af3e-4e47-ac7e-512b8f1c01e1
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Internet Sales-fbfafabd-d7f8-4835-9563-3f62d81176b6' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Power BI Security\Data\AdventureWorksDW.xlsx"), null, true),
				    FactInternetSales_Sheet = Source{[Item="FactInternetSales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactInternetSales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"PromotionKey", Int64.Type}, {"CurrencyKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"SalesOrderNumber", type text}, {"SalesOrderLineNumber", Int64.Type}, {"RevisionNumber", Int64.Type}, {"OrderQuantity", Int64.Type}, {"UnitPrice", type number}, {"ExtendedAmount", type number}, {"UnitPriceDiscountPct", Int64.Type}, {"DiscountAmount", Int64.Type}, {"ProductStandardCost", type number}, {"TotalProductCost", type number}, {"SalesAmount", type number}, {"TaxAmt", type number}, {"Freight", type number}, {"CarrierTrackingNumber", type text}, {"CustomerPONumber", type text}, {"OrderDate", type date}, {"DueDate", type date}, {"ShipDate", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"CurrencyKey", "CustomerPONumber", "RevisionNumber", "PromotionKey"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

