table Product
	lineageTag: d285e741-432b-44a2-8c90-0bed29a7f28b

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8c6f3e95-749a-4604-b659-74352f3a005e
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SizeUnitMeasureCode
		dataType: string
		lineageTag: 93ea1788-f047-43e4-8476-2aa5ea32090f
		summarizeBy: none
		sourceColumn: SizeUnitMeasureCode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column EnglishProductName
		dataType: string
		lineageTag: c9830b3a-0d4c-43ba-8df4-6eaded7bf787
		summarizeBy: none
		sourceColumn: EnglishProductName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StandardCost
		dataType: string
		lineageTag: c03a764f-3091-4153-80bc-9a1d197adcc9
		summarizeBy: none
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column FinishedGoodsFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6a9e0b5b-10a1-4ca9-9a8e-f61351996b4c
		summarizeBy: none
		sourceColumn: FinishedGoodsFlag

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: b3e6d3b1-a839-474c-a6cb-822c827b0a3c
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SafetyStockLevel
		dataType: int64
		formatString: 0
		lineageTag: 2f32fcf2-4521-45af-8868-0e649d052fc7
		summarizeBy: sum
		sourceColumn: SafetyStockLevel

		annotation SummarizationSetBy = Automatic

	column ReorderPoint
		dataType: int64
		formatString: 0
		lineageTag: 1c351634-fd4a-4a7d-879f-b01a214f3e29
		summarizeBy: sum
		sourceColumn: ReorderPoint

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: string
		lineageTag: e9d88078-02ea-416f-9716-4ba281af7f55
		summarizeBy: none
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Size
		dataType: string
		lineageTag: 28e143d8-c650-4d5a-8574-0e63fca43a93
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SizeRange
		dataType: string
		lineageTag: 6ffd8902-9d8c-4fca-9654-590c6d452170
		summarizeBy: none
		sourceColumn: SizeRange

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column DaysToManufacture
		dataType: int64
		formatString: 0
		lineageTag: 26cc1d0c-25f0-430e-aff3-5aea5cd163f1
		summarizeBy: sum
		sourceColumn: DaysToManufacture

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 714e0c91-ad1c-4003-ae50-4b8f52ad7d32
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column DealerPrice
		dataType: string
		lineageTag: 3fd66ce5-4540-4bb1-a459-7f540d7a2004
		summarizeBy: none
		sourceColumn: DealerPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Class
		dataType: string
		lineageTag: 3bc95f77-539b-4250-a62a-abdb3f741356
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ModelName
		dataType: string
		lineageTag: 3e1416e0-0610-43e3-bab7-3e1a6be85041
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column EnglishDescription
		dataType: string
		lineageTag: 9a598457-f08f-422a-989a-688061886b3f
		summarizeBy: none
		sourceColumn: EnglishDescription

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 60d2cada-51f2-4982-84d3-eab8218a7540
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: string
		lineageTag: ad912999-462d-4c55-be76-8d6a778e98af
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Status
		dataType: string
		lineageTag: 03032e5e-95b0-4045-b7b0-c601cd67f499
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Product-7d960425-0150-43a2-88f8-40b2d188fda0 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Power BI Security\Data\AdventureWorksDW.xlsx"), null, true),
				    DimProduct_Sheet = Source{[Item="DimProduct",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimProduct_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductAlternateKey", type text}, {"ProductSubcategoryKey", type any}, {"WeightUnitMeasureCode", type text}, {"SizeUnitMeasureCode", type text}, {"EnglishProductName", type text}, {"SpanishProductName", type text}, {"FrenchProductName", type text}, {"StandardCost", type any}, {"FinishedGoodsFlag", type logical}, {"Color", type text}, {"SafetyStockLevel", Int64.Type}, {"ReorderPoint", Int64.Type}, {"ListPrice", type any}, {"Size", type text}, {"SizeRange", type text}, {"Weight", Int64.Type}, {"DaysToManufacture", Int64.Type}, {"ProductLine", type text}, {"DealerPrice", type any}, {"Class", type text}, {"Style", type text}, {"ModelName", type text}, {"LargePhoto", type any}, {"EnglishDescription", type text}, {"FrenchDescription", type text}, {"ChineseDescription", type text}, {"ArabicDescription", type text}, {"HebrewDescription", type text}, {"ThaiDescription", type text}, {"GermanDescription", type text}, {"JapaneseDescription", type text}, {"TurkishDescription", type text}, {"StartDate", type date}, {"EndDate", type any}, {"Status", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"FrenchDescription", "FrenchProductName", "GermanDescription", "HebrewDescription", "JapaneseDescription", "ProductSubcategoryKey", "ProductAlternateKey", "LargePhoto", "ArabicDescription", "SpanishProductName", "ThaiDescription", "TurkishDescription", "WeightUnitMeasureCode", "Weight", "Style", "ChineseDescription"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

