table Customer
	lineageTag: 82ff92a4-b749-4b53-ae27-f440ddcffa20

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 92264167-fc5a-4cec-b30a-22931d1e59bb
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 70221499-df8a-4ac9-98fa-4ef9d759c978
		summarizeBy: none
		sourceColumn: GeographyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 08effe4d-cc07-4848-8bac-0877336b8dba
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column FirstName
		dataType: string
		lineageTag: f1512430-a9e0-414a-b24e-fdcb4dd2392e
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column MiddleName
		dataType: string
		lineageTag: dd673006-5fdd-4906-a3f8-b6a941f1a758
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column LastName
		dataType: string
		lineageTag: 1a6a51ad-dd86-47fa-a3de-8f9c0625f68f
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column NameStyle
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dce9846b-08c0-4dca-b3b2-e6b86e2bc845
		summarizeBy: none
		sourceColumn: NameStyle

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc35db6f-5885-4f57-9a73-2681267e85d6
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 26d05c76-173f-41cb-ac96-f117ce7452aa
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Suffix
		dataType: string
		lineageTag: 209b0edb-90f4-493d-b1ed-c80ce5917a1d
		summarizeBy: none
		sourceColumn: Suffix

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Gender
		dataType: string
		lineageTag: 41a2e4a7-5754-44a6-a3bf-fa9039994686
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column EmailAddress
		dataType: string
		lineageTag: 32c0f32f-10ce-48b2-a7a9-7321ca2e76e2
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column YearlyIncome
		dataType: int64
		formatString: 0
		lineageTag: 20cd2b4b-835e-406e-96b5-05a8f89b6171
		summarizeBy: none
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 2a95959f-228f-4388-a44a-520781da8660
		summarizeBy: none
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column NumberChildrenAtHome
		dataType: int64
		formatString: 0
		lineageTag: 834eab12-de45-4b90-bcb8-a212d6f5001d
		summarizeBy: none
		sourceColumn: NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: int64
		formatString: 0
		lineageTag: 9c8b6695-4eae-4628-b586-6778a3ce852b
		summarizeBy: none
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: f66e6352-0deb-4d8c-9b58-5689f4b735f9
		summarizeBy: none
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		lineageTag: f6c7ae73-a8ff-4d17-822a-9af4715a95ba
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column AddressLine2
		dataType: string
		lineageTag: 4785204b-54c0-4c17-b74e-b5392a061ee7
		summarizeBy: none
		sourceColumn: AddressLine2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Phone
		dataType: string
		lineageTag: 920aa71a-28f1-4a2f-8bd3-3dbe62989498
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column DateFirstPurchase
		dataType: dateTime
		formatString: Long Date
		lineageTag: e7e44feb-eac2-4c9d-8bd7-d55b82d7d67b
		summarizeBy: none
		sourceColumn: DateFirstPurchase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CommuteDistance
		dataType: string
		lineageTag: 94e08756-fc61-4cee-89ed-5131b90544ec
		summarizeBy: none
		sourceColumn: CommuteDistance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Full Name' = 'Customer'[FirstName] & " " & Customer[LastName]
		lineageTag: cd78140a-5cf3-43e4-b7f1-1264abe127cb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Age = DATEDIFF('Customer'[BirthDate], TODAY(),YEAR)
		formatString: 0
		lineageTag: 27379628-120c-4af4-94e2-4d3f4de78689
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Age Breakdown' =
			IF('Customer'[Age] >= 55, "55+",
			                IF('Customer'[Age] >= 35, "35-54",
			                IF('Customer'[Age] >= 25, "25-34", "18-24")))
		lineageTag: c178e9a8-c91c-4ced-b4ad-0bdbfe6e0848
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Customer-b7a9612f-8839-42fb-8bea-61504b74ad3e = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Power BI Security\Data\AdventureWorksDW.xlsx"), null, true),
				    DimCustomer_Sheet = Source{[Item="DimCustomer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimCustomer_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"GeographyKey", Int64.Type}, {"CustomerAlternateKey", type text}, {"Title", type text}, {"FirstName", type text}, {"MiddleName", type text}, {"LastName", type text}, {"NameStyle", type logical}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Suffix", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"YearlyIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"NumberChildrenAtHome", Int64.Type}, {"EnglishEducation", type text}, {"SpanishEducation", type text}, {"FrenchEducation", type text}, {"EnglishOccupation", type text}, {"SpanishOccupation", type text}, {"FrenchOccupation", type text}, {"HouseOwnerFlag", Int64.Type}, {"NumberCarsOwned", Int64.Type}, {"AddressLine1", type text}, {"AddressLine2", type text}, {"Phone", type text}, {"DateFirstPurchase", type date}, {"CommuteDistance", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"CustomerAlternateKey", "EnglishEducation", "EnglishOccupation", "FrenchEducation", "FrenchOccupation", "SpanishEducation", "SpanishOccupation"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

