table FactInternetSales_Test
	lineageTag: d3b80a4a-05bd-42ed-87ac-8576a3c34ca7

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 16
		incrementalGranularity: year
		incrementalPeriods: 15
		sourceExpression =
			let
			    Source = Sql.Databases("localhost"),
			    PracticeDB = Source{[Name="PracticeDB"]}[Data],
			    dbo_FactInternetSales_Test = PracticeDB{[Schema="dbo",Item="FactInternetSales_Test"]}[Data],
			    #"Filtered Rows" = Table.SelectRows(dbo_FactInternetSales_Test, each [OrderDate] >= RangeStart and [OrderDate] < RangeEnd)
			in
			    #"Filtered Rows"

	column SalesOrderNumber
		dataType: string
		lineageTag: ad7c50c0-1e47-4e80-9225-13b988093c6f
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 8d9cc70b-85e7-46b6-ba2c-4070e56b7b8a
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ce655406-6c5f-476e-98c8-cd8d0a003a6b
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column TaxAmt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 30b65bf6-5602-4b67-9b35-852ecba4fe36
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 0ced4b54-091d-4bdf-9216-52e6cecba5ef
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: d0bfee12-5cd0-4dd9-821d-eccb57ae2360
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column OrderDate_Year = YEAR(FactInternetSales_Test[OrderDate])
		formatString: 0
		lineageTag: c7cc19bf-4074-4433-8f76-3832cc2b4dc6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FactInternetSales_Test = m
		mode: import
		source =
				let
				    Source = Sql.Databases("localhost"),
				    PracticeDB = Source{[Name="PracticeDB"]}[Data],
				    dbo_FactInternetSales_Test = PracticeDB{[Schema="dbo",Item="FactInternetSales_Test"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_FactInternetSales_Test, each [OrderDate] >= RangeStart and [OrderDate] < RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

