table dimLocation
	lineageTag: 4607e103-5ae0-4862-a46b-19f043bb5197

	column LocationKey
		dataType: double
		formatString: 0
		lineageTag: c97cd30f-e01c-4001-b070-c96112721ab9
		summarizeBy: none
		sourceColumn: LocationKey

		annotation SummarizationSetBy = Automatic

	column GeographyType
		dataType: string
		lineageTag: e495c7f5-edef-46ee-83ac-6c09f10eb805
		summarizeBy: none
		sourceColumn: GeographyType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Continent
		dataType: string
		lineageTag: 60966a14-4866-4aed-8d90-e2dd7a96e6a7
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column City
		dataType: string
		lineageTag: 87bfc415-dbea-412f-b1ed-6defb87ff424
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column State
		dataType: string
		lineageTag: aa740150-20a9-41d7-9a89-7b2c553de50d
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Country
		dataType: string
		lineageTag: fce5b9a1-0982-427c-a2a3-1c3e618b9842
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Geometry
		dataType: string
		lineageTag: 07eb5721-5d1d-4648-988a-396c58fcd1b8
		summarizeBy: none
		sourceColumn: Geometry

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition dimLocation-207c0514-2d25-443e-b676-968bdf6806a3 = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = InputForDimTables,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"DimStore"}),
				    #"Expanded DimStore" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimStore", {"DimGeography"}, {"DimGeography"}),
				    #"Expanded DimGeography" = Table.ExpandRecordColumn(#"Expanded DimStore", "DimGeography", {"GeographyKey", "GeographyType", "ContinentName", "CityName", "StateProvinceName", "RegionCountryName", "Geometry"}, {"GeographyKey", "GeographyType", "ContinentName", "CityName", "StateProvinceName", "RegionCountryName", "Geometry"}),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded DimGeography", {"GeographyKey"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Duplicates",{{"GeographyKey", Order.Ascending}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Sorted Rows",894,765,Replacer.ReplaceValue,{"GeographyKey"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","North America","Europe",Replacer.ReplaceText,{"ContinentName"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","North Harford","Munich",Replacer.ReplaceText,{"CityName"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Maryland","Bavaria",Replacer.ReplaceText,{"StateProvinceName"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","United States","Germany",Replacer.ReplaceText,{"RegionCountryName"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","POINT (-76.3641 39.5837)","POINT (11.5755 48.1432)",Replacer.ReplaceText,{"Geometry"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value5",{{"GeographyKey", "LocationKey"}, {"ContinentName", "Continent"}, {"CityName", "City"}, {"StateProvinceName", "State"}, {"RegionCountryName", "Country"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation PBI_QueryRelationships = {"columnCount":7,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/dimLocation/Replaced Value.{GeographyKey,0}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimGeography.{GeographyType,1}","Section1/dimLocation/Replaced Value1.{ContinentName,2}","Section1/dimLocation/Replaced Value2.{CityName,3}","Section1/dimLocation/Replaced Value3.{StateProvinceName,4}","Section1/dimLocation/Replaced Value4.{RegionCountryName,5}","Section1/dimLocation/Replaced Value5.{Geometry,6}"],"ColumnCount":7,"KeyColumnNames":[],"ColumnIdentities":["Section1/dimLocation/Replaced Value.{GeographyKey,0}","Server.Database\\/2/SQL/datatraining\\\\mssqlserver2019;ContosoRetailDW/dbo/DimGeography.{GeographyType,1}","Section1/dimLocation/Replaced Value1.{ContinentName,2}","Section1/dimLocation/Replaced Value2.{CityName,3}","Section1/dimLocation/Replaced Value3.{StateProvinceName,4}","Section1/dimLocation/Replaced Value4.{RegionCountryName,5}","Section1/dimLocation/Replaced Value5.{Geometry,6}"],"RelationshipInfo":[]}

