table dimProduct
	lineageTag: 8ad9270d-5885-4f06-b077-4ea87d2f0839

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 37fb66d9-7c01-495e-8926-756d0893dbc9
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 460a6740-53c1-4707-b2d0-97480eec0e2c
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Manufacturer
		dataType: string
		lineageTag: 10f5c141-48ed-4396-a285-495009b04ac5
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ClassName
		dataType: string
		lineageTag: 456d67ef-6494-4f86-8d0c-501afa04b62e
		summarizeBy: none
		sourceColumn: ClassName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StyleName
		dataType: string
		lineageTag: 695bc92a-774c-421b-b41d-ff8630f2c67d
		summarizeBy: none
		sourceColumn: StyleName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ColorName
		dataType: string
		lineageTag: 6c2e84fa-fc1d-4ca1-8bc0-303ce7618add
		summarizeBy: none
		sourceColumn: ColorName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StockTypeName
		dataType: string
		lineageTag: fa1bc94e-1055-4d85-8a94-6e2c74bff8a0
		summarizeBy: none
		sourceColumn: StockTypeName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column UnitCost
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 71b897e1-8106-4ecd-b834-54f18abf5e1e
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column UnitPrice
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: ab9eb58c-166f-438c-8702-ea8768884662
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column ProductSubcategory
		dataType: string
		lineageTag: 4196c0a6-69e1-4066-851a-3a19af1424a3
		summarizeBy: none
		sourceColumn: ProductSubcategory

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ProductCategory
		dataType: string
		lineageTag: c770f4f5-abf0-44ac-b0da-8b94052ed8ba
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition dimProduct-ef19de9e-5bfd-4116-bb42-f35a610586ba = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = InputForDimTables,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"DimProduct - Copy"}),
				    #"Expanded DimProduct - Copy" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimProduct - Copy", {"ProductKey", "ProductLabel", "ProductName", "ProductDescription", "ProductSubcategoryKey", "Manufacturer", "BrandName", "ClassID", "ClassName", "StyleID", "StyleName", "ColorID", "ColorName", "Size", "SizeRange", "SizeUnitMeasureID", "Weight", "WeightUnitMeasureID", "UnitOfMeasureID", "UnitOfMeasureName", "StockTypeID", "StockTypeName", "UnitCost", "UnitPrice", "AvailableForSaleDate", "StopSaleDate", "Status", "DimProductSubcategory"}, {"ProductKey", "ProductLabel", "ProductName", "ProductDescription", "ProductSubcategoryKey", "Manufacturer", "BrandName", "ClassID", "ClassName", "StyleID", "StyleName", "ColorID", "ColorName", "Size", "SizeRange", "SizeUnitMeasureID", "Weight", "WeightUnitMeasureID", "UnitOfMeasureID", "UnitOfMeasureName", "StockTypeID", "StockTypeName", "UnitCost", "UnitPrice", "AvailableForSaleDate", "StopSaleDate", "Status", "DimProductSubcategory"}),
				    #"Expanded DimProductSubcategory" = Table.ExpandRecordColumn(#"Expanded DimProduct - Copy", "DimProductSubcategory", {"ProductSubcategoryName", "DimProductCategory"}, {"ProductSubcategoryName", "DimProductCategory"}),
				    #"Expanded DimProductCategory" = Table.ExpandRecordColumn(#"Expanded DimProductSubcategory", "DimProductCategory", {"ProductCategoryName"}, {"ProductCategoryName"}),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded DimProductCategory", {"ProductKey"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Duplicates",{{"ProductKey", Order.Ascending}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Sorted Rows",{"ProductKey", "ProductName", "Manufacturer", "ClassName", "StyleName", "ColorName", "StockTypeName", "UnitCost", "UnitPrice", "ProductSubcategoryName", "ProductCategoryName"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Other Columns1","Contoso","Teclip",Replacer.ReplaceText,{"ProductName", "Manufacturer", "ProductSubcategoryName"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Wide World Importers","Cybric",Replacer.ReplaceText,{"ProductName", "Manufacturer", "ProductSubcategoryName"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Northwind Traders","Audiolog",Replacer.ReplaceText,{"ProductName", "Manufacturer", "ProductSubcategoryName"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Fabrikam","Harics",Replacer.ReplaceText,{"ProductName", "Manufacturer", "ProductSubcategoryName"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Adventure Works","Koder",Replacer.ReplaceText,{"ProductName", "Manufacturer", "ProductSubcategoryName"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Proseware","Digiwatts",Replacer.ReplaceText,{"ProductName", "Manufacturer", "ProductSubcategoryName"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Southridge Video","Screencast",Replacer.ReplaceText,{"Manufacturer"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","The Phone Company","Telephoniq",Replacer.ReplaceText,{"Manufacturer"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7",", Ltd","",Replacer.ReplaceText,{"Manufacturer"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8",", Inc.","",Replacer.ReplaceText,{"Manufacturer"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","WWI","Cybric",Replacer.ReplaceText,{"ProductName"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","The Phone Company","Telephoniq",Replacer.ReplaceText,{"ProductName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value11",{{"ProductCategoryName", "ProductCategory"}, {"ProductSubcategoryName", "ProductSubcategory"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

