table Metrics
	lineageTag: d2a93611-7445-4949-b0dd-b83467821e4f

	measure 'Total Sales' = SUM(fctSales[SalesAmount])
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		displayFolder: Other
		lineageTag: 00742927-6d3d-43d2-af5d-205795ae406d

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Sales - Forecast' = SUM(fctForecast[SalesAmountQuota])
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		displayFolder: Other
		lineageTag: 3ffce6c8-34a7-4041-bafa-e4d7c6b7b8fa

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Sales - YTD' = TOTALYTD([Total Sales], dimDate[Date])
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		displayFolder: Other
		lineageTag: 12ab46dd-6556-4bfb-ad41-de5d3c6a6d1a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Sales - Forecast - YTD' = TOTALYTD([Total Sales - Forecast], dimDate[Date])
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		displayFolder: Other
		lineageTag: cfc8745f-0489-41cf-a8cc-2d83bd94e0d9

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Sales > Forecast' =
			
			IF(
			    [Total Sales]>[Total Sales - Forecast],
			    1,
			    0
			)
		formatString: 0
		displayFolder: Other
		lineageTag: 093032f7-a551-4b17-a7b5-8d926d5a39de

	measure 'Button Text' = ```
			
			VAR ValidSelection = 
			ISFILTERED(dimProduct[Manufacturer])
			&& HASONEVALUE(dimProduct[Manufacturer])
			VAR Result = 
			IF(
			    ValidSelection,
			    "See details for " & SELECTEDVALUE(dimProduct[Manufacturer]),
			    "Select one manufacturer"
			)
			RETURN
			    Result
			```
		lineageTag: 6d6cfe3b-a7ec-4e76-9f34-3f94de4b8365

		annotation PBI_FormatHint = {"isText":true}

	measure 'Tooltip Text - Disabled' = ```
			"Select a single manufacturer" 
			```
		lineageTag: 952ef40d-9b17-42a6-9774-ebb7def08fd0

		annotation PBI_FormatHint = {"isText":true}

	measure 'Tooltip Text - Enabled' = "Click to see more details for " & SELECTEDVALUE(dimProduct[Manufacturer])
		lineageTag: 97024e81-b469-4710-9771-acee8f55c3b8

		annotation PBI_FormatHint = {"isText":true}

	measure Drillthrough = ```
			
			VAR Destination = SELECTEDVALUE('Destinations Drillthrough'[Destinations])
			VAR ValidSelection = 
			ISFILTERED(dimStore[StoreName]) 
			&& HASONEVALUE(dimStore[StoreName])
			&& ISFILTERED(dimProduct[Manufacturer])
			&& HASONEVALUE(dimProduct[Manufacturer])
			VAR Result = 
			IF(
			    ValidSelection,
			    Destination
			)
			RETURN
			    Result
			```
		lineageTag: 6fdf7c5e-c793-41be-aa8d-ba6b9bf23937

		annotation PBI_FormatHint = {"isText":true}

	measure AP_Button_Text = ```
			
			VAR selection = ISFILTERED(dimProduct[Manufacturer])
			RETURN 
			    IF (
			        selection && HASONEVALUE(dimProduct[Manufacturer]),
			        "See details for " & SELECTEDVALUE(dimProduct[Manufacturer]),
			        "Select One Manufacturer"
			    )
			```
		lineageTag: 4884faf9-513b-468a-8903-cbdc6c6f916e

	measure AP_Drillthrough_btn = ```
			
			VAR Destination = SELECTEDVALUE('Destinations Drillthrough'[Destinations])
			VAR Manu_Selection = ISFILTERED(dimProduct[Manufacturer]) 
			&& HASONEVALUE(dimProduct[Manufacturer])
			
			VAR Store_Selection = ISFILTERED(dimStore[StoreName]) 
			&& HASONEVALUE(dimStore[StoreName])
			
			VAR CODE =
			 IF ( Manu_Selection && Store_Selection,
			     Destination
			 )
			RETURN CODE
			
			```
		lineageTag: b159be0b-db46-4add-8295-820476b6520b

	partition Metrics-046ac0f4-6588-468c-9ad3-724e4e699f29 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

