table '_ Measures'
	lineageTag: eaaba4eb-a7c4-4fcc-9401-b455fd9213ff

	measure 'Total Sales' =
			
			SUMX(
			    Sales,
			    RELATED(Products[Price])*Sales[Units]
			)
		formatString: #,0.00
		lineageTag: 22e846aa-132a-4413-948f-db1162297abe

	measure 'Total Units' = SUM(Sales[Units])
		formatString: 0
		lineageTag: 7cda261f-c875-449f-94eb-74558d8b2416

	measure 'Unique Days' =
			
			SUMX(
			    VALUES(Sales[Channel]),
			    CALCULATE(DISTINCTCOUNT(Sales[Date]))
			)
		formatString: 0
		lineageTag: ed52c12b-b073-4bd5-b7ae-2b4c796cb5f6

	measure Measure = HASONEVALUE('Calendar'[Month])
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6aff6ef5-f81f-454a-820b-37b9584258d5

	measure 'Max Sold Per Day' =
			
			MAXX(
			    'Calendar',
			    [Total Sales]
			)
		lineageTag: 550954b6-f43f-4b63-8949-1133295c2bf7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Trasaction Value' =
			
			SUMX(
			    Products,
			    CALCULATE(MAX(Sales[Sales]))
			)
		formatString: #,0
		lineageTag: 75f22f78-da59-44bf-8eb7-5e129de13dac

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Max Sold Per Day Correct' =
			
			SUMX(
			    SUMMARIZE (
			        Sales,
			        'Calendar'[Year],
			        Products[Category]
			    ),
			    [Max Sold Per Day]
			)
		lineageTag: 2482ff16-d941-43a6-841b-ec155409cc3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '.'
		isHidden
		lineageTag: 7f009680-9ea1-45a6-a697-51efaa207672
		summarizeBy: none
		isNameInferred
		sourceColumn: [.]

		annotation SummarizationSetBy = Automatic

	partition '_ Measures-3be0531a-e29f-4aac-ac66-f648258d3fb3' = calculated
		mode: import
		source = ```
				
				    DATATABLE(
				        ".", STRING,
				        {
				            {" "}
				        }
				    )
				```

	annotation PBI_Id = 86a42d1c34ec41fb8a5603f08c36557f

